# Generated by Django 3.1.5 on 2021-01-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot_rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='imageUploaded',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='images',
            name='image_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotornot_rater.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='images',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='images',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='images',
            name='isHot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='isNot',
            field=models.IntegerField(default=0),
        ),
    ]
