# Generated by Django 3.0.3 on 2021-01-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot_rater', '0002_auto_20210124_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=24)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
