# Generated by Django 3.0.3 on 2021-01-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot_rater', '0003_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='choice_text',
            new_name='city',
        ),
    ]
