# Generated by Django 3.0.3 on 2021-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot_rater', '0004_auto_20210124_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='city',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
