# Generated by Django 3.0.3 on 2021-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot_rater', '0005_auto_20210124_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imageUploaded',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
