# Generated by Django 3.0.3 on 2021-01-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot_rater', '0006_auto_20210124_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_user',
        ),
    ]
